pipeline {
    environment {
        projectName = "Test job"
    }
    options {
		buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))    
	}
    agent {
        node {
            label 'slave2'
        }
    }
    stages {
        stage('Run newman') {
            options {
                timeout(time: 10, unit: 'MINUTES')
            }
            steps {
				sh label: 'Newman Execution', script: '''
					#mkdir report
					newman run Test/SimpleBooksApi/Books_APIs.postman_collection.json -e Test/SimpleBooksApi/Books_APIs.postman_environment.json --reporters cli,junit --reporter-junit-export report/report.xml
				'''.stripIndent()
            }
            post {
                always {
                    script {
                        println " **** Publish test results **** "
                        archiveArtifacts artifacts: 'report/report.xml', fingerprint: true
                        junit allowEmptyResults: true, testResults:'report/report.xml'
                      	cleanWs()
                    }
                }
            }
        }

        stage("Report Junit") {
            steps {
                junit allowEmptyResults: true, testResults: 'report/report.xml'
            }
        }
    }
}
