pipeline {
    environment {
        projectName = "Test job"
        mailTo = "nguyendinhnghia.ut@gmail.com"
    }
    options {
		buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))    
	}
    agent {
        node {
            label 'master'
        }
    }
    stages {
        stage('Check out git') {
            options {
                timeout(time: 10, unit: 'MINUTES')
            }
            steps {
				sh label: 'Newman Execution', script: '''
					mkdir report
					newman run Test/SimpleBooksApi/Books_APIs.postman_collection.json -e Test/SimpleBooksApi/Books_APIs.postman_environment.json --reporters junit --reporter-junit-export report/report.xml
				'''.stripIndent()
            }
            post {
                always {
                    script {
                        println " **** Publish test results **** "
                        archiveArtifacts artifacts: 'report/report.xml', fingerprint: true
                        junit allowEmptyResults: true, testResults:'report/report.xml'
                      	cleanWs()
                    }
                }
                failure {
                    emailext body: '''${SCRIPT, template="groovy-html.template"}''',
                    mimeType: 'text/html',
                    subject: "[Jenkins] Test suite is failed - Please check!",
                    to: env.mailTo
                }
                unstable {
                    emailext body: '''${SCRIPT, template="groovy-html.template"}''',
                    mimeType: 'text/html',
                    subject: "[Jenkins] Test suite is unstable - Please check!",
                    to: env.mailTo
                }
                success {
                    emailext body: '''${SCRIPT, template="groovy-html.template"}''',
                    mimeType: 'text/html',
                    subject: "[Jenkins] Test suite is success!",
                    to: env.mailTo
                }
            }
        }

        stage("Report Junit") {
            steps {
                junit allowEmptyResults: true, testResults: 'report/report.xml'
            }
        }
    }
}
